################################################################################
# everything that is starting with disallow uses permission, if value is true  #
# possible message variables  %user, %server, %core                            #
# possible timemessage variables %time                                         #
################################################################################
message:
  enable-Messages: true
  message: user% on server% running v% b% on core% ! n% It's time% !  
  firstjoin:  It's the first time
  privatejoinmessage: online%
  leftmessage: Player user% left server% !
  whitelist-message: You aren't whitelisted on this server
  banmessage: You are a Bunny! You got banned from this server
  serverfullmessage: I'm sorry! The Server is full!
  maintenance_message: Server is under construction
  maintenance_mode: false
  enable-random-chatcolor: true
  timeformat: MMM dd, yyyy HH%dpmm
commandLogger: true
timezone: 2
world-setting:
  Blockcreeper: true
  prevent-tnt: true
  Blockender: true
  xpsave: true
  prevent-fire-spread: true
  prevent-lava-spread: true
  general-spread: true
  flint-and-steal-spread: true
  strike-spread: true
advertising:
  plugin-advert: true
  time-between-adverts: 300
  advert-message: SmartServerTool
  advert-prefix: [News]
config-save-interval: 150
drops:
  glass-sand-drop: true
  glassPane-drop: true
  diamond-ore-drop: true
  apple-drop: true
  goldenapple-shear: true
chance:
  diamond-drop-rate: 3
  apple-drop-rate: 3
  glass-sand-drop-rate: 1
  glassPane-drop-rate: 1
Misc:
  Save-Player-PressPlate: false
  item-amount: 20
  Sleeping-Ignored: false
  adminchat-password: SST
Question:
  answer: peace
  unlockGroupName: Builder
  question: What word doesn't match in the rules??
Join:
  Player: false
disable-physics:
  Gravel: false
  Sand: false
  Torch: true
  Trapdoor: true
disable:
  permission: false