language: java
jdk:
- oraclejdk8
sudo: false
notifications:
  email:
    on_failure: always
    on_success: never
addons:
  apt:
    packages:
    - oracle-java8-installer
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hGI6YJZWBYQC5CrxX7z4oklJw9FdaJgSWqwJJSvXpJdYp+YxNBHdkoLzyIiyrkVghW33ZDDifwi+oD79zrZ3fodoxcLiIsRfljTbLOVhzOXWlMxlBffpFSiL6YhNEn42pA4W05TgN32rws5Er00wbWu3bNqHAf39V2EHo8toOu0=
  file: "./target/Smart-Server-Tool-*.jar"
  on:
    repo: yannicklamprecht/Smart-Server-Tool
    tags: true
