Crafting:
  EntchantmentTable: false
  SpawnEggs: false
  Wheat: true
  Grass: true
  CobbleStone: true
  Net: true
  Saddle: true
  LongGrass: true
  Chain:
   Helmet: true
   Chest: true
   Legg: true
   Feet: true
  CommandBlock: true
Furnace:
  GlowStone: true
  IronIngot: true
  GoldIngot: true
  Diamond: true
  NetherBrick: true
  Sponge: true