name: SmartServerTool
version: 1.6.2 Rewrote
main: com.ysl3000.plugin.SmartServerTool
authors:
      - DEV ysl3000
description: provides you some simple Server Commands! This mostly refers to a Vanilla-like server.
commands:
 /admin:
  usage: //admin
  description: Toggle Op & Gamemode
  permission: sst.admin
  permission-message: You don't have sst.admin
 gmc:
  usage: /gmc
  description: Set Creative
  permission: sst.gamemode
  permission-message: You don't have sst.gamemode
 gms:
  usage: /gms
  description: Set Survival
  permission: sst.gamemode
  permission-message: You don't have sst.gamemode
 gm:
  usage: /gm
  description: Current GameMode
  permission: sst.gm
  permission-message: You don't have sst.gm
 td:
  usage: /td
  description: set Time to Day
  permission: sst.time
  permission-message: You don't have sst.time
 tn:
  usage: /tn
  description: set Time to Night
  permission: sst.time
  permission-message: You don't have sst.time
 sun:
  usage: /sun
  description: Set Sun
  permission: sst.weather
  permission-message: You don't have sst.weather
 storm:
  usage: /storm
  description: Set Storm
  permission: sst.weather
  permission-message: You don't have sst.weather
 wg:
  usage: /wg
  description: get Weather
  permission: sst.wg
  permission-message: You don't have sst.wg
 km:
  usage: /km
  description: kill's yourself
  permission: sst.km
  permission-message: sst.km
 kill:
  usage: /kill <player>
  description: kill player
  permission: sst.kill
  permission-message: sst.kill
 heal:
  usage: /heal <player>
  description: heal
  permission: sst.heal
  permission-message: sst.heal
 /ip:
  usage: //ip <player>
  description: get ip of player
  permission: sst.ip
  permission-message: sst.ip
 switch:
  usage: /switch <player>
  description: tp to player and player tp to old location
  permission: sst.switch
  permisssion-message: sst.switch
 setsp:
  usage: /setsp
  description: setspawn
  permission: sst.setsp
  permission-message: sst.setsp
 spawn:
  usage: /spawn
  description: Teleport to Spawn
  permission: sst.spawn
  permission-message: sst.spawn
 home:
  usage: /home
  description: teleport to home
  permission: sst.home
  permission-message: sst.home 
 mod:
  usage: /mod
  description: enter modmode
  permission: sst.mod
  permission-message: sst.mod
 fly:
  usage: /fly <player>
  description: toggle fly
  permission: sst.fly
  permission-message: sst.fly
 back:
  usage: /back
  description: teleport to last location
 done:
  usage: /done
  description: leave modmode
  permission: sst.mod
  permission-message: sst.mod
 fs:
   usage: /fs <amount>
   description: set flyspeed
 ws:
   usage: /ws <amount>
   description: set walkspeed
 god:
  usage: /god
  permission: sst.god
 online:
  flagrate: [list]
  usage: /list
  description: lists onlineplayer
 seen:
  usage: /seen
  description: check first&last seen
 freeze:
  usage: /freeze <player>
  description: freezes a player
  permission: sst.freeze
  permission-message: sst.freeze
 healme:
  usage: /healme
  permission: sst.healme
 info:
  usage: /info
  permission: sst.serverinfo
 rt:
  usage: /rt
permissions:
    sst.*:
         description: give all permission
         children:
             sst.admin: true
             sst.mod: true
             sst.gamemode: true
             sst.gm: true
             sst.time: true
             sst.weather: true
             sst.km: true
             sst.kill: true
             sst.wg: true
             sst.heal: true
             sst.tp: true
             sst.tpo: true
             sst.ip: true
             sst.switch: true
             sst.setsp: true
             sst.spawn: true
             sst.seth: true
             sst.home: true
             sst.ci: true
             sst.fly: true
             sst.visible: true
             sst.item: true
             sst.repair: true
             sst.nolog: true
             sst.gamemode: true
             sst.flyo: true
             sst.cansee: true
             sst.info: true
             sst.create: true
             sst.gmo: true
             sst.joinfull: true
             sst.joinservice: true
             sst.chat: true
             sst.move: true
             sst.changetype: true
             sst.plugins: true
    sst.nolog:
         description: No Logging of Commands
         default: false
    sst.gamemodeo:
         description: allow entering other people gmc
         default: false
    sst.gamemodeo:
         description: allow entering other people gms
         default: false
    sst.flyo:
         description: allow you to enable others to fly
         default: false
    sst.cansee:
         description: you can see hidden player
         default: false
    sst.info:
         description: allow playerinfo
         default: op
    sst.create:
         description: allows creating buildings
    sst.gmo:
         description: allow you looking up others gamemode
    sst.joinfull:
         description: allows you to join full server
    sst.joinservice:
         description: allows you to join server while in servicemode
    sst.autofly:
         description: enables fly on join
         default: false
    sst.chat:
         description: enables chatting
         default: op
    sst.move:
         description: enables moving
         default: op
    sst.changetype:
         description: allows changing mobspawner
         default: false
    sst.vwbench:
         description: allows opening vwbench
         op: true
    sst.vechest:
         description: allows opening vechest
         op: true
    sst.vetable:
         description: allows opening vetable
         op: true
    sst.cMc:
         description: allows crafting MagmaContainer
         op: true
    sst.openanychest:
         description: you can open any chest
         op: true